version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.x

  pre_build:
    commands:
      - cd cicd
      - chmod +x install-terraform.sh configure-named-profile.sh apply-terraform.sh
      - ./install-terraform.sh
      - ./configure-named-profile.sh

  buid:
    commands:
      - ./apply-terraform.sh